### ISSUE TITLE
First level, main camera stuck on CMVEndStageCame

### ISSUE THREAD

**Issue by jdelgado2002** [kidagine/MarioRunReplica#1]
On game start, the live camera gets set to CMVEndStageCame and doesn't change to follow the character

![cameraOnEnding](https://user-images.githubusercontent.com/2649871/62430576-0db0cc80-b6e4-11e9-9b1d-883a614c170d.gif)

**Comment by kidagine** [comment]
Very late response, I fixed the issue, it as a small silly mistake with the Priority order between the endGame and inGame cameras, thanks a lot for letting me know!
